### ISSUE TITLE
Small documentation change for Python Bindings

### ISSUE THREAD

**Issue by sistemicorp** [itas109/CSerialPort#87]
**Describe the bug**
It was not clear how to build Python bindings from the instructions.

**To Reproduce**
Current Build instructions:
```
  mkdir bin
  cd bin
  cmake .. 
  cmake --build . --config Release
```

**Additional context**
Suggestion:
```
cd bindings/python
mkdir bin
cd bin
cmake .. 
cmake --build . --config Release
```

**Comment by itas109** [comment]
Thanks for your suggestions.
I will test it with ESP32.

**Comment by itas109** [comment]
I tested the master code of Python. It works fine.

Could you test the master code?

Open the following comments at python\CMakeLists.txt
```
# add_definitions(-DCSERIALPORT_DEBUG) # CSerialPort Debug Mode
```
This way, the application will output debug info to console and log.

CSerialPort_20240515.log
```
[INFO] itas109::CSerialPort::CSerialPort - OS: Windows, Arch: x86_64, Compiler: vs2022(1932), Bit: 64, C++: 201402L, Version: https://github.com/itas109/CSerialPort - V4.3.1.240204
[INFO] CSerialPortWinBase::openPort - portName: COM4, baudRate: 9600, dataBit: 8, parity: 0, stopBit: 0, flowControl: 0, mode: async, readBufferSize:4096(4096), readIntervalTimeoutMS: 0, minByteReadNotify: 1
[INFO] CSerialPortWinBase::openPort - open COM4. code: 0, message: success
[INFO] CSerialPortWinBase::writeData - write. len: 5, hex(top100): 3132333435
[INFO] CSerialPortWinBase::writeData - write. len: 7, hex(top100): 69746173313039
[INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 1). len: 1, hex(top100): 31
[INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 1
 [INFO] CSerialPortWinBase::readData - read. len: 1, hex(top100): 31
```

**Comment by sistemicorp** [comment]
Result,
```
(venv312) C:\git\a43-P1150\stm\stm32h750xbh\tools>python main.py
2024-05-15 10:59:29.761 [INFO] itas109::CSerialPort::CSerialPort - OS: Windows, Arch: x86_64, Compiler: vs2022(1937), Bit: 64, C++: 201402L, Version: https://github.com/itas109/CSerialPort - V4.3.1.240204
Version: https://github.com/itas109/CSerialPort - V4.3.1.240204

Available Friendly Ports:
1 - COM3 STMicroelectronics serial
2 - COM4 STMicroelectronics Virtual COM Port
Please Input The Index Of Port(1 - 2)
2
Port Name: COM4
2024-05-15 10:59:35.947 [INFO] CSerialPortWinBase::openPort - portName: COM4, baudRate: 115200, dataBit: 8, parity: 0, stopBit: 0, flowControl: 0, mode: async, readBufferSize:4096(4096), readIntervalTimeoutMS: 0, minByteReadNotify: 1
2024-05-15 10:59:35.954 [INFO] CSerialPortWinBase::openPort - open COM4. code: 0, message: success
Open COM4 Success
send: len 16 - 000e03a1616668636d645f70696e6700
2024-05-15 10:59:35.957 [INFO] CSerialPortWinBase::writeData - write. len: 16, hex(top100): 30303065303361313631363636383633
waiting...
...............................................................................................................2024-05-15 10:59:47.034 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 440). len: 440, hex(top100): 000438011001000000041C01101D40282329302E302D3338392D67643466613864612D6373657269616C01000002F80210010103FE01000000048007100100000004280F100A696C6F61645F7365740101010101010106A0941A7D42000000000004C403
2024-05-15 10:59:47.035 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 440
..
(venv312) C:\git\a43-P1150\stm\stm32h750xbh\tools>
```
At the end, the program just came back to the prompt... I didn't stop it.

**Comment by itas109** [comment]
```
SENT: 000e03a1616668636d645f70696e6700
LOG:  30303065303361313631363636383633
```
send is same with log.
send format is ascii data.
log format is hex data.
0x30 ....

**Comment by itas109** [comment]
```
SENT: 000e03a1616668636d645f70696e6700
LOG:  30303065303361313631363636383633
```
send is same with log.
send format is ascii data.
log format is hex data.
0x30 ....

**Comment by sistemicorp** [comment]
I fixed formatting so things match in the above log.

**Comment by sistemicorp** [comment]
Could it be a Python version problem?
Or a Swig version problem?  I used Swig 4.2.1, whereas your instructions have 4.1.1.
I can try Swig 4.1.1...

**Comment by itas109** [comment]
My python version 3.10.

Could you test the receive function with VSPD(Virtual Serial Port Driver)?

In this way, the program is not affected by the hardware.

**Comment by sistemicorp** [comment]
Do you mean with CDC serial driver?  I have been using `pyserial` for my application and it works with my target.

However I am sending a lot of data and running into a Python GIL problem to read the serial data fast enough before Windows buffers overflow.  I am running more tests to try and truly understand the nature of my problem using pyserial.  With WireShark I am able to see the serial data packets and frames and they are good.  However on the PC, I get packet decode errors and I see that some data is just missing, and I see large values of `pyserial.inWaiting()`, like >50k bytes, and I have delays in reading serial of up to 20ms.

Your CSerialPort interests me because you create your own thread and buffer to read serial, and that means your read loop will be outside of the Python GIL, and should read serial port no matter what Python is doing.

I don't know much about swig and how it creates the Python bindings, but my feeling is thats where the problem is.

**Comment by itas109** [comment]
Could you use the C++ program CSerialPortDemoNoGui to test the receive problem?

If CSerialPortDemoNoGui also crash, we could use Visual Studio debug it for more information.

```
cd CSerialPort
mkdir bin && cd bin
cmake ..
cmake --build .
cd bin
./CSerialPortDemoNoGui
```

**Comment by sistemicorp** [comment]
That seems to work, specifically,
```
 Directory of C:\git\CSerialPort\bin\bin\Release

2024-05-16  10:13 AM    <DIR>          .
2024-05-14  12:48 PM    <DIR>          ..
2024-05-14  12:48 PM            61,440 CSerialPortDemoNoGui.exe
2024-05-16  10:13 AM        11,012,467 CSerialPort_20240516.log
2024-05-14  12:49 PM            44,544 libcserialport.dll
```
Running it the console fills up very fast, here is a snippet from the log,
```
2024-05-16 10:13:27.916 [INFO] itas109::CSerialPort::CSerialPort - OS: Windows, Arch: x86_64, Compiler: vs2022(1937), Bit: 64, C++: 201402L, Version: https://github.com/itas109/CSerialPort - V4.3.1.240204
2024-05-16 10:13:33.199 [INFO] CSerialPortWinBase::openPort - portName: COM4, baudRate: 9600, dataBit: 8, parity: 0, stopBit: 0, flowControl: 0, mode: async, readBufferSize:4096(4096), readIntervalTimeoutMS: 0, minByteReadNotify: 1
2024-05-16 10:13:33.206 [INFO] CSerialPortWinBase::openPort - open COM4. code: 0, message: success
2024-05-16 10:13:33.206 [INFO] CSerialPortWinBase::writeData - write. len: 5, hex(top100): 3132333435
2024-05-16 10:13:33.207 [INFO] CSerialPortWinBase::writeData - write. len: 7, hex(top100): 69746173313039
2024-05-16 10:13:34.960 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 24). len: 24, hex(top100): 00010102100668656C6C6F04618415020101010100000000
2024-05-16 10:13:34.960 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 24
2024-05-16 10:13:34.960 [INFO] CSerialPortWinBase::readData - read. len: 24, hex(top100): 00010102100668656C6C6F04618415020101010100000000
2024-05-16 10:13:34.961 [INFO] CSerialPortWinBase::writeData - write. len: 24, hex(top100): 00010102100668656C6C6F04618415020101010100000000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 28). len: 28, hex(top100): 0004E4011005FEFFFFFF0101010100000004B8011001010101010000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 28
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::readData - read. len: 28, hex(top100): 0004E4011005FEFFFFFF0101010100000004B8011001010101010000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::writeData - write. len: 28, hex(top100): 0004E4011005FEFFFFFF0101010100000004B8011001010101010000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 12). len: 12, hex(top100): 0004B8011001010101010000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 12
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::readData - read. len: 12, hex(top100): 0004B8011001010101010000
2024-05-16 10:13:34.962 [INFO] CSerialPortWinBase::writeData - write. len: 12, hex(top100): 0004B8011001010101010000
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 24). len: 24, hex(top100): 0004B80110010101010100000004B8011001010101010000
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 24
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::readData - read. len: 24, hex(top100): 0004B80110010101010100000004B8011001010101010000
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::writeData - write. len: 24, hex(top100): 0004B80110010101010100000004B8011001010101010000
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::commThreadMonitor - write buffer(usedLen 12). len: 12, hex(top100): 0004B8011001010101010000
2024-05-16 10:13:34.963 [INFO] CSerialPortWinBase::commThreadMonitor - onReadEvent. portName: COM4, readLen: 12
```
I didn't decode anything to see if this my expected data...
CSerialPort did not creash.

I do have a Python 3.10 virtual environment, but when I try to run `main.py`, I get,
```
(venv) C:\git\a43-P1150\stm\stm32h750xbh\tools>python main.py
Traceback (most recent call last):
  File "C:\git\a43-P1150\stm\stm32h750xbh\tools\main.py", line 10, in <module>
    import cserialport
  File "C:\git\a43-P1150\stm\stm32h750xbh\tools\cserialport.py", line 12, in <module>
    import _cserialport
ImportError: DLL load failed while importing _cserialport: The specified module could not be found.
```
I tried putting the DLL local in this directory but that didn't help.

The Python 3.12 venv the import does succeed, but port doesn't work as previously reported above.

**Comment by itas109** [comment]
I test different version python.

windows 10
cmake 3.22.1
vs2022
swig 4.1.1, 4.2.1
python 3.12.3 crash, 3.10.11 work fine

**Comment by sistemicorp** [comment]
Thank you.  The Python 3.12 result at leat matches my result.
Re Python 3.10, I don't know why DLL fails to import.  The CSerialPort Python bindings files are identical when I build them with Python 3.10 or 3.12, or with Swig 4.1.1 or 4.2.1.

I am in less of a hurry now, as I resolved a problem with `pyserial` so I am unblocked on my product.

But I am interested still in CSerialPort because I have some low level processing that I would like to move out of Python and into C++ and your project might be ideal for that.

Thank you so much for trying.
I will watch this project for any update will retry at that time.

**Comment by itas109** [comment]
Sorry for the long wait, the crash problem has been fixed.
